name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Sync files
        run: bash .github/workflows/sync.sh

      - name: Deploy master
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: dist
          publish_branch: deploy
          # https://github.com/peaceiris/actions-gh-pages/issues/163
          exclude_assets: ''
          force_orphan: true
          commit_message: 'deploy'

